version: "3.4"

services:
  webapp:
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    image: nginx:1.13.9
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.http.conf:/etc/nginx/nginx.conf
      - ./dist/app:/app
